import { FaBook, FaUser, FaMoneyBillAlt, FaEnvelope } from 'react-icons/fa';
import { FaGear } from 'react-icons/fa6';
export const panel = [
  {
    name: "O'quv reja",
    icons: FaBook,
    items: [
      { item_name: "O'quv reja", target: '/education/curriculum' },
      { item_name: 'Dars jadvali', target: '/education/time-table'},
      { item_name: 'Nazorat jadvali', target: '#' },
      { item_name: 'Fan resurslari', target: '#' },
      { item_name: 'Davomat', target: '#' },
      { item_name: 'Davomat hisoboti', target: '#' },
      { item_name: "O'zlashtirish", target: '#' },
      { item_name: 'Shaxsiy qaydnoma', target: '#' },
      { item_name: 'Imtihonlar', target: '#' },
      { item_name: 'Reyting daftarcha', target: '#' },
      { item_name: 'Fan tanlovi', target: '#' },
    ],
  },
  {
    name: "Qayta o'qish",
    icons: FaBook,
    items: [
      { item_name: "Ariza qayta o'qish", target: '#' },
      { item_name: "Q.O'qish mashg'ulotlari", target: '#' },
      { item_name: "Q.O'qish nazorat jadvali", target: '#' },
      { item_name: "Q.O'qish o'zlashtirish", target: '#' },
    ],
  },
  {
    name: "Talaba ma'lumoti",
    icons: FaUser,
    items: [
      { item_name: 'Rezyume', target: '#' },
      { item_name: 'Buyruqlar', target: '#' },
      { item_name: 'Shartnomalar', target: '#' },
      { item_name: "Ma'lumotnomalar", target: '#' },
      { item_name: 'Talaba hujjati', target: '#' },
      { item_name: 'Bitiruv varaqa', target: '#' },
      { item_name: 'Talaba GPA bali', target: '#' },
      { item_name: "Shaxsiy ma'lumotlar", target: '#' },
      { item_name: 'Bitiruv ishi', target: '#' },
    ],
  },
  {
    name: "Moliyaviy to'lov",
    icons: FaMoneyBillAlt,
    items: [
      { item_name: "Kontrakt ro'yhati", target: '#' },
      { item_name: 'Stipendiya hisobi', target: '#' },
    ],
  },
  {
    name: 'Xabarlar',
    icons: FaEnvelope,
    items: [
      { item_name: 'Mening xabarlarim', target: '#' },
      { item_name: 'Xabar yaratish', target: '#' },
    ],
  },
  {
    name: 'Tizim',
    icons: FaGear,
    items: [
      { item_name: 'Profil', target: '#' },
      { item_name: "So'rovnoma", target: '#' },
      { item_name: 'Kirish tarixi', target: '#' },
    ],
  },
];

export const accordions = [
  {
    name: 'Fanlar va resurslar',
    items: [
      {
        item_name: "O'quv reja",
        target: '/education/curriculum',
        img: 'assets/image/book.png',
      },
      { item_name: 'Dars jadvali', target: '/education/time-table', img: 'assets/image/calendar.png' },
      {
        item_name: 'Nazorat jadvali',
        target: '#',
        img: 'assets/image/Achievement.png',
      },
      { item_name: 'Fan tanlovi', target: '#', img: '../assets/image/Target.png' },
      { item_name: 'Fan resurslari', target: '#', img: 'assets/image/PC.png' },
      { item_name: 'Unilibrary', target: '#', img: 'assets/image/PC.png' },
    ],
  },
  {
    name: "O'quv faoliyati",
    items: [
      { item_name: 'Davomat', target: '#', img: 'assets/image/clock.png' },
      { item_name: "O'zlashtirish", target: '#', img: 'assets/image/Calc.png' },
      { item_name: 'Reyting daftarcha', target: '#', img: 'assets/image/book.png' },
      { item_name: 'Imtihonlar', target: '#', img: 'assets/image/question.png' },
      { item_name: 'Bitiruv ishi', target: '#', img: 'assets/image/book.png' },
    ],
  },
  {
    name: "Qayta o'qish",
    items: [
      { item_name: "Ariza qayta o'qish", target: '#', img: 'assets/image/book.png' },
      {
        item_name: "Q.O'qish mashg'ulotlari",
        target: '#',
        img: 'assets/image/calendar.png',
      },
      {
        item_name: "Q.O'qish nazorat jadvali",
        target: '#',
        img: 'assets/image/Achievement.png',
      },
      {
        item_name: "Q.O'qish o'zlashtirish",
        target: '#',
        img: 'assets/image/Calc.png',
      },
    ],
  },
  {
    name: "Hujjatlar ro'yhati",
    items: [
      { item_name: 'Buyruqlar', target: '#', img: 'assets/image/Note.png' },
      { item_name: 'Shartnomalar', target: '#', img: 'assets/image/list.png' },
      { item_name: "Ma'lumotnomalar", target: '#', img: 'assets/image/list.png' },
      { item_name: 'Bitiruv varaqa', target: '#', img: 'assets/image/book.png' },
      { item_name: 'Talaba hujjati', target: '#', img: 'assets/image/list.png' },
      { item_name: 'Talaba hujjati', target: '#', img: 'assets/image/message.png' },
    ],
  },
];

export const study_table = [
  {
    date: '( 04 sentabr, 2023 / 20 yanvar, 2024 )',
    table: [
      {
        fan_nomi: "O'zbekistonning eng yangi tarixi",
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 60,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Xorijiy til',
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 0,
          seminar: 0,
          amaliy: 60,
          mustaqil: 60,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Hisob',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: 'Fizika',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: 'Dasturlash',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: 'Akademik yozuv',
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 60,
          jami: 120,
        },
      },
    ],
  },
  {
    date: '( 22 yanvar, 2024 / 01 iyun, 2024 )',
    table: [
      {
        fan_nomi: "Dinshunoslik",
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 60,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Falsafa',
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 60,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Xorijiy til',
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 0,
          seminar: 0,
          amaliy: 30,
          mustaqil: 90,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Fizika',
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 16,
          seminar: 0,
          amaliy: 14,
          mustaqil: 90,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Differensial tenglamalar',
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 60,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Diskret tuzilmalar',
        fan_turi: 'Majburiy',
        yuklama: 120,
        kredit: 4.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 60,
          jami: 120,
        },
      },
      {
        fan_nomi: 'Dasturlash',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 120,
          jami: 180,
        },
      },
    ],
  },
  {
    date: '( 04 sentabr, 2024 / 20 yanvar, 2025 )',
    table: [
      {
        fan_nomi: "Ma'lumotlar bazasi",
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 0,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: 'Kiberxavfsizlik asoslari',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 44,
          seminar: 0,
          amaliy: 46,
          mustaqil: 90,
          jami: 180,
        },
      },
      {
        fan_nomi: "Ma'lumotlar tuzilmasi va algoritmlar",
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 30,
          amaliy: 30,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: 'Kompyuterni tashkil etish',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: 'Elektronika va sxemalar',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 60,
          mustaqil: 90,
          jami: 180,
        },
      },
    ],
  },
  {
    date: '( 22 yanvar, 2025 / 01 iyun, 2025 )',
    table: [
      {
        fan_nomi: "Kompyuter tarmoqlari",
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: "Sun'iy intellekt asoslari",
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: 'Web ilovalarni yaratish',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: '	Ehtimollik va statistika',
        fan_turi: 'Majburiy',
        yuklama: 180,
        kredit: 6.0,
        about: {
          maruza: 30,
          seminar: 0,
          amaliy: 30,
          mustaqil: 120,
          jami: 180,
        },
      },
      {
        fan_nomi: "Yangi tahrirdagi O'zbekiston Respublikasi Konstitutsiyasi",
        fan_turi: 'Majburiy',
        yuklama: 60,
        kredit: 2.0,
        about: {
          maruza: 16,
          seminar: 0,
          amaliy: 14,
          mustaqil: 30,
          jami: 60,
        },
      },
      {
        fan_nomi: 'Jismoniy tarbiya',
        fan_turi: 'Majburiy',
        yuklama: 60,
        kredit: 2.0,
        about: {
          maruza: 0,
          seminar: 0,
          amaliy: 44,
          mustaqil: 16,
          jami: 60,
        },
      },
      {
        fan_nomi: 'Kasbiy nutq madaniyati',
        fan_turi: 'Majburiy',
        yuklama: 60,
        kredit: 2.0,
        about: {
          maruza: 20,
          seminar: 0,
          amaliy: 24,
          mustaqil: 16,
          jami: 60,
        },
      },
    ],
  },
];
